name: ytquran
description: A new Flutter project.
publish_to: 'none'

version: 1.0.5+12

environment:
  sdk: '>=2.19.0-120.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.8
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.15

#  Added Dependencies
  
  # google_mobile_ads: ^0.13.0

  google_fonts: ^6.1.0
  
  
  youtube_player_flutter: ^8.1.2
  
  # adhan: ^1.1.16
  location: ^5.0.3
  flutter_qiblah: ^2.1.0
  geolocator: ^9.0.2
  flutter_svg: ^2.0.9
  
  sound_mode: ^2.0.2
  provider: ^6.0.2
  intl: ^0.18.1
  introduction_screen: ^3.0.2
  url_launcher: ^6.0.18
  share_plus: ^7.2.1
  android_alarm_manager_plus: ^3.0.3
  real_volume: ^1.0.6
  disable_battery_optimization: ^1.1.0+1
  clear_all_notifications: ^1.0.0
  http: ^1.1.0

  flutter_map: ^6.0.1
  prayers_times: ^0.0.1
  geocoding: ^2.1.0
  hijri: ^3.0.0
  workmanager: ^0.5.1
  flutter_local_notifications: ^16.1.0
  shared_preferences: ^2.2.1
  flutter_compass: ^0.7.0
  google_maps_flutter: ^2.5.0
  flutter_config: ^2.0.2
  dio: ^5.3.2
  flutter_polyline_points: ^2.0.0
  scrollview_observer: ^1.16.5
  flutter_carousel_slider: ^1.1.0
  percent_indicator: ^4.2.3
  numberpicker: ^2.1.2
  smooth_page_indicator: ^1.1.0
  vibration: ^1.8.1
  animated_splash_screen: ^1.3.0

  hexcolor: ^3.0.1
  


    

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/quran.png
  android: true
  ios: true
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/svgs/
    - assets/datas/

  fonts:
    - family: quran
      fonts:
        - asset: assets/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: assets/me_quran.ttf
