name: ytquran
description: A new Flutter project.
publish_to: 'none'

version: 1.0.5+12

environment:
  sdk: '>=2.19.0-120.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  scrollable_positioned_list: ^0.2.3
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.15

#  Added Dependencies
  # flutter_hijri_date: ^0.2.0
  # google_mobile_ads: ^0.13.0

  google_fonts: ^3.0.1
  
  dio: ^4.0.6
  youtube_player_flutter: ^8.1.2
  hijri: ^3.0.0
  # adhan: ^1.1.16
  location: ^4.3.0
  flutter_qiblah: ^2.1.0
  geolocator: ^9.0.2
  flutter_svg: ^1.1.6
  
  flutter_local_notifications: ^9.6.1
  sound_mode: ^2.0.2
  provider: ^6.0.2
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  url_launcher: ^6.0.18
  share_plus: ^4.0.10
  android_alarm_manager_plus: ^2.0.7
  real_volume: ^1.0.6
  disable_battery_optimization: ^1.1.0+1
  clear_all_notifications: ^0.0.3
  http: ^0.13.6
  
  


    

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/quran.png
  android: true
  ios: true
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/svgs/
    - assets/datas/

  fonts:
    - family: quran
      fonts:
        - asset: assets/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: assets/me_quran.ttf
